version: '2'
services:
  broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
  ctrl:
    build: ./ctrl
    volumes:
      - ./ctrl:/work
    working_dir: /work
    command: node ctrl.js
  trainer:
    build: ./trainer
    links:
      - broker
    volumes:
      - ./trainer:/work
    working_dir: /work
    command: python app.py
  app:
    build: ./app
    links:
      - broker
      - ctrl
    volumes:
      - ./app:/work
    working_dir: /work
    restart: always
    command: node app.js
  www:
    image: nginx
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./www:/work
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/htpasswd:/etc/nginx/htpasswd
