version: '2'
services:
  ctrl:
    build: ./ctrl
    networks:
      - default
    volumes:
      - ./ctrl:/work
    working_dir: /work
    command: node ctrl.js

  trainer:
    build: ./trainer
    networks:
      - default
    volumes:
      - ./trainer:/work
    working_dir: /work
    command: python app.py

  app:
    build: ./app
    networks:
      - default
    volumes:
      - ./app:/work
    working_dir: /work
    restart: always
    command: node app.js

  www:
    image: nginx
    ports:
      - 80:80
    networks:
      - default
    volumes:
      - ./www:/work
      - ./www/nginx.conf:/etc/nginx/nginx.conf
      - ./www/htpasswd:/etc/nginx/htpasswd
