version: '2'
services:
  broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
  trainer:
    build: ./trainer
    links: 
      - broker
    volumes:
      - ./trainer:/work
    working_dir: /work
    command: python app.py
  app:
    build: ./app
    ports:
      - 3000:3000
    links:
      - broker
    volumes:
      - ./app:/work
    working_dir: /work
    restart: always
    command: node app.js
